### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Chu4nQ1n** [unitreerobotics/unitree_rl_gym#1]
开发人员您好，

我在执行教程中[RL控制例程](https://support.unitree.com/home/zh/developer/rl_example)时遇到以下报错

`
/home/chuan/anaconda3/envs/rl-go2/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

Traceback (most recent call last):
  File "train.py", line 20, in <module>
    train(args)

  File "train.py", line 14, in train
    ppo_runner, train_cfg = task_registry.make_alg_runner(env=env, name=args.task, args=args)

  File "/home/chuan/rsl_rl/unitree_rl_gym/legged_gym/utils/task_registry.py", line 119, in make_alg_runner
    runner = OnPolicyRunner(env, train_cfg_dict, log_dir, device=args.rl_device)

  File "/home/chuan/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 29, in __init__
    obs, extras = self.env.get_observations()

ValueError: too many values to unpack (expected 2)
`

导致了gym界面闪退，在按照[其他博主经验](https://blog.csdn.net/fyc300/article/details/133134490)修改pytoch源代码后错误仍然存在。

针对此问题希望能够得到您的帮助，谢谢。

**Comment by Chu4nQ1n** [comment]
重新安装 [rsl_rl v1.0.2](https://github.com/leggedrobotics/rsl_rl/releases/tag/v1.0.2) 后解决问题。
