### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by xuqingquan1995** [unitreerobotics/unitree_rl_gym#20]
使用GPU运行例程出错
日志如下：
(rl-go2) unitree@unitree-QNLXS:~/robot/go2_rl/unitree_rl_gym/legged_gym/scripts$ python train.py --task=go2
Importing module 'gym_38' (/home/unitree/robot/go2_rl/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/unitree/robot/go2_rl/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0+cu113
Device count 1
/home/unitree/robot/go2_rl/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/unitree/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /home/unitree/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Setting seed: 1
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
/home/unitree/miniconda3/envs/rl-go2/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    train(args)
  File "train.py", line 12, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/unitree/robot/go2_rl/unitree_rl_gym/legged_gym/utils/task_registry.py", line 68, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/unitree/robot/go2_rl/unitree_rl_gym/legged_gym/envs/base/legged_robot.py", line 41, in __init__
    super().__init__(self.cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/unitree/robot/go2_rl/unitree_rl_gym/legged_gym/envs/base/base_task.py", line 55, in __init__
    self.create_sim()
  File "/home/unitree/robot/go2_rl/unitree_rl_gym/legged_gym/envs/base/legged_robot.py", line 199, in create_sim
    self._create_envs()
  File "/home/unitree/robot/go2_rl/unitree_rl_gym/legged_gym/envs/base/legged_robot.py", line 571, in _create_envs
    pos[:2] += torch_rand_float(-1., 1., (2,1), device=self.device).squeeze(1)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)
使用cpu可以正常运行
显卡为4060，笔记本

**Comment by xuqingquan1995** [comment]
更新为最新版本的驱动，cuda，pytorch后解决
