### ISSUE TITLE
Tensors must have same number of dimensions: got 2 and 1

### ISSUE THREAD

**Issue by Yisikanadai** [unitreerobotics/unitree_rl_gym#27]
tot_iter = self.current_learning_iteration + num_learning_iterations
        for it in range(self.current_learning_iteration, tot_iter):
            start = time.time()
            # Rollout
            with torch.inference_mode():
                for i in range(self.num_steps_per_env):
                    print(obs.shape)
                    print(critic_obs.shape)
                    actions = self.alg.act(obs, critic_obs)
                    print(actions.shape)
                    obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
                    critic_obs = privileged_obs if privileged_obs is not None else obs
                    obs, critic_obs, rewards, dones = obs.to(self.device), critic_obs.to(self.device), rewards.to(self.device), dones.to(self.device)
                    self.alg.process_env_step(rewards, dones, infos)
 
 
 
 I modified the rsl_rl_1.0.2/rsl_rl/runners/on_policy_runnner.py to print the shape of antion because it is wrong
 
 The code error is as follows:

/home/ubuntu417/anaconda3/envs/go2_rl/bin/python unitree_rl_gym-main/legged_gym/scripts/train.py --task=go2 
Importing module 'gym_38' (/home/ubuntu417/unitree_go2/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/ubuntu417/unitree_go2/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.13.0+cu116
Device count 1
/home/ubuntu417/unitree_go2/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/ubuntu417/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Emitting ninja build file /home/ubuntu417/.cache/torch_extensions/py38_cu116/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Loading extension module gymtorch...
ninja: no work to do.
Setting seed: 1
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
/home/ubuntu417/anaconda3/envs/go2_rl/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Actor MLP: Sequential(
  (0): Linear(in_features=48, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=12, bias=True)
)
Critic MLP: Sequential(
  (0): Linear(in_features=48, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=1, bias=True)
)
step action: torch.Size([4096, 12])
compute_observations torch.Size([4096, 12])
torch.Size([4096, 48])
compute_observations
step
torch.Size([48])
torch.Size([48])
torch.Size([12])
step action: torch.Size([12])
compute_observations torch.Size([12])
Traceback (most recent call last):
  File "unitree_rl_gym-main/legged_gym/scripts/train.py", line 18, in <module>
    train(args)
  File "unitree_rl_gym-main/legged_gym/scripts/train.py", line 14, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/ubuntu417/unitree_go2/rsl_rl-1.0.2/rsl_rl/runners/on_policy_runner.py", line 112, in learn
    obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
  File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 74, in step
    self.post_physics_step()
  File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 110, in post_physics_step
    self.compute_observations() # in some cases a simulation step might be required to refresh some obs (for example body positions)
  File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 189, in compute_observations
    self.obs_buf = torch.cat((  self.base_lin_vel * self.obs_scales.lin_vel,
RuntimeError: Tensors must have same number of dimensions: got 2 and 1

**Comment by craipy-hub** [comment]
Check the state of the network input and check the network type is LSTM or MLP

**Comment by Yisikanadai** [comment]
> Check the state of the network input and check the network type is LSTM or MLP

the network type is  MLP
here is the network
```
Actor MLP: Sequential(
  (0): Linear(in_features=48, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=12, bias=True)
)
Critic MLP: Sequential(
  (0): Linear(in_features=48, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=1, bias=True)
)
```
here is the network input
```
obs[0]shape: torch.Size([48]) ,obs[1]shape: torch.Size([48])
critic_obs[0]shape: torch.Size([48]) ,critic_obs[1]shape: torch.Size([48])
```
the  learn code is here
```
    def learn(self, num_learning_iterations, init_at_random_ep_len=False):
        # initialize writer
        if self.log_dir is not None and self.writer is None:
            self.writer = SummaryWriter(log_dir=self.log_dir, flush_secs=10)
        if init_at_random_ep_len:
            self.env.episode_length_buf = torch.randint_like(self.env.episode_length_buf, high=int(self.env.max_episode_length))
        obs = self.env.get_observations()
        privileged_obs = self.env.get_privileged_observations()
        critic_obs = privileged_obs if privileged_obs is not None else obs
        print("obs[0]shape:",obs[0].shape,",obs[1]shape:",obs[1].shape)
        print("critic_obs[0]shape:",obs[0].shape,",critic_obs[1]shape:",obs[1].shape)
        obs = obs[0].to(self.device)      ## change
        critic_obs = critic_obs[0].to(self.device)         ## change
        self.alg.actor_critic.train() # switch to train mode (for dropout for example)

        ep_infos = []
        rewbuffer = deque(maxlen=100)
        lenbuffer = deque(maxlen=100)
        cur_reward_sum = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)
        cur_episode_length = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)

        tot_iter = self.current_learning_iteration + num_learning_iterations
        for it in range(self.current_learning_iteration, tot_iter):
            start = time.time()
            # Rollout
            with torch.inference_mode():
                for i in range(self.num_steps_per_env):
                    actions = self.alg.act(obs, critic_obs)
                    obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
                    critic_obs = privileged_obs if privileged_obs is not None else obs
                    obs, critic_obs, rewards, dones = obs.to(self.device), critic_obs.to(self.device), rewards.to(self.device), dones.to(self.device)
                    self.alg.process_env_step(rewards, dones, infos)
.......
```
I try to change `obs = obs.to(self.device) ` to  `obs = obs[0].to(self.device) ` 
but get a new error
```
Actor MLP: Sequential(
  (0): Linear(in_features=48, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=12, bias=True)
)
Critic MLP: Sequential(
  (0): Linear(in_features=48, out_features=512, bias=True)
  (1): ELU(alpha=1.0)
  (2): Linear(in_features=512, out_features=256, bias=True)
  (3): ELU(alpha=1.0)
  (4): Linear(in_features=256, out_features=128, bias=True)
  (5): ELU(alpha=1.0)
  (6): Linear(in_features=128, out_features=1, bias=True)
)
obs[0]shape: torch.Size([48]) ,obs[1]shape: torch.Size([48])
critic_obs[0]shape: torch.Size([48]) ,critic_obs[1]shape: torch.Size([48])
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 18, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 14, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/ubuntu417/unitree_go2/rsl_rl-1.0.2/rsl_rl/runners/on_policy_runner.py", line 114, in learn
    obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
  File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 74, in step
    self.post_physics_step()
  File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 110, in post_physics_step
    self.compute_observations() # in some cases a simulation step might be required to refresh some obs (for example body positions)
  File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 182, in compute_observations
    self.obs_buf = torch.cat((  self.base_lin_vel * self.obs_scales.lin_vel,
RuntimeError: Tensors must have same number of dimensions: got 2 and 1
```
I find the code is here
```
    def compute_observations(self):
        """ Computes observations
        """
        print((self.base_lin_vel * self.obs_scales.lin_vel).shape)
        print((self.base_ang_vel  * self.obs_scales.ang_vel).shape)
        print((self.commands[:, :3] * self.commands_scale).shape)
        print(((self.dof_pos - self.default_dof_pos) * self.obs_scales.dof_pos).shape)
        print((self.dof_vel * self.obs_scales.dof_vel).shape)
        print((self.actions).shape)
        self.obs_buf = torch.cat((  self.base_lin_vel * self.obs_scales.lin_vel,
                                    self.base_ang_vel  * self.obs_scales.ang_vel,
                                    self.projected_gravity,
                                    self.commands[:, :3] * self.commands_scale,
                                    (self.dof_pos - self.default_dof_pos) * self.obs_scales.dof_pos,
                                    self.dof_vel * self.obs_scales.dof_vel,
                                    self.actions
                                    ),dim=-1)
        # add perceptive inputs if not blind
        # add noise if needed
        if self.add_noise:
            self.obs_buf += (2 * torch.rand_like(self.obs_buf) - 1) * self.noise_scale_vec
```
the output is 
```
torch.Size([4096, 3])
torch.Size([4096, 3])
torch.Size([4096, 3])
torch.Size([4096, 12])
torch.Size([4096, 12])
torch.Size([12])
```

**Comment by Yisikanadai** [comment]
> > Check the state of the network input and check the network type is LSTM or MLP
> 
> Thanks to reply!!!
> 
> the network type is MLP here is the network
> 
> ```
> Actor MLP: Sequential(
>   (0): Linear(in_features=48, out_features=512, bias=True)
>   (1): ELU(alpha=1.0)
>   (2): Linear(in_features=512, out_features=256, bias=True)
>   (3): ELU(alpha=1.0)
>   (4): Linear(in_features=256, out_features=128, bias=True)
>   (5): ELU(alpha=1.0)
>   (6): Linear(in_features=128, out_features=12, bias=True)
> )
> Critic MLP: Sequential(
>   (0): Linear(in_features=48, out_features=512, bias=True)
>   (1): ELU(alpha=1.0)
>   (2): Linear(in_features=512, out_features=256, bias=True)
>   (3): ELU(alpha=1.0)
>   (4): Linear(in_features=256, out_features=128, bias=True)
>   (5): ELU(alpha=1.0)
>   (6): Linear(in_features=128, out_features=1, bias=True)
> )
> ```
> 
> here is the network input
> 
> ```
> obs[0]shape: torch.Size([48]) ,obs[1]shape: torch.Size([48])
> critic_obs[0]shape: torch.Size([48]) ,critic_obs[1]shape: torch.Size([48])
> ```
> 
> the learn code is here
> 
> ```
>     def learn(self, num_learning_iterations, init_at_random_ep_len=False):
>         # initialize writer
>         if self.log_dir is not None and self.writer is None:
>             self.writer = SummaryWriter(log_dir=self.log_dir, flush_secs=10)
>         if init_at_random_ep_len:
>             self.env.episode_length_buf = torch.randint_like(self.env.episode_length_buf, high=int(self.env.max_episode_length))
>         obs = self.env.get_observations()
>         privileged_obs = self.env.get_privileged_observations()
>         critic_obs = privileged_obs if privileged_obs is not None else obs
>         print("obs[0]shape:",obs[0].shape,",obs[1]shape:",obs[1].shape)
>         print("critic_obs[0]shape:",obs[0].shape,",critic_obs[1]shape:",obs[1].shape)
>         obs = obs[0].to(self.device)      ## change
>         critic_obs = critic_obs[0].to(self.device)         ## change
>         self.alg.actor_critic.train() # switch to train mode (for dropout for example)
> 
>         ep_infos = []
>         rewbuffer = deque(maxlen=100)
>         lenbuffer = deque(maxlen=100)
>         cur_reward_sum = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)
>         cur_episode_length = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)
> 
>         tot_iter = self.current_learning_iteration + num_learning_iterations
>         for it in range(self.current_learning_iteration, tot_iter):
>             start = time.time()
>             # Rollout
>             with torch.inference_mode():
>                 for i in range(self.num_steps_per_env):
>                     actions = self.alg.act(obs, critic_obs)
>                     obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
>                     critic_obs = privileged_obs if privileged_obs is not None else obs
>                     obs, critic_obs, rewards, dones = obs.to(self.device), critic_obs.to(self.device), rewards.to(self.device), dones.to(self.device)
>                     self.alg.process_env_step(rewards, dones, infos)
> .......
> ```
> 
> I try to change `obs = obs.to(self.device) ` to `obs = obs[0].to(self.device) ` but get a new error
> 
> ```
> Actor MLP: Sequential(
>   (0): Linear(in_features=48, out_features=512, bias=True)
>   (1): ELU(alpha=1.0)
>   (2): Linear(in_features=512, out_features=256, bias=True)
>   (3): ELU(alpha=1.0)
>   (4): Linear(in_features=256, out_features=128, bias=True)
>   (5): ELU(alpha=1.0)
>   (6): Linear(in_features=128, out_features=12, bias=True)
> )
> Critic MLP: Sequential(
>   (0): Linear(in_features=48, out_features=512, bias=True)
>   (1): ELU(alpha=1.0)
>   (2): Linear(in_features=512, out_features=256, bias=True)
>   (3): ELU(alpha=1.0)
>   (4): Linear(in_features=256, out_features=128, bias=True)
>   (5): ELU(alpha=1.0)
>   (6): Linear(in_features=128, out_features=1, bias=True)
> )
> obs[0]shape: torch.Size([48]) ,obs[1]shape: torch.Size([48])
> critic_obs[0]shape: torch.Size([48]) ,critic_obs[1]shape: torch.Size([48])
> Traceback (most recent call last):
>   File "legged_gym/scripts/train.py", line 18, in <module>
>     train(args)
>   File "legged_gym/scripts/train.py", line 14, in train
>     ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
>   File "/home/ubuntu417/unitree_go2/rsl_rl-1.0.2/rsl_rl/runners/on_policy_runner.py", line 114, in learn
>     obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
>   File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 74, in step
>     self.post_physics_step()
>   File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 110, in post_physics_step
>     self.compute_observations() # in some cases a simulation step might be required to refresh some obs (for example body positions)
>   File "/home/ubuntu417/unitree_go2/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py", line 182, in compute_observations
>     self.obs_buf = torch.cat((  self.base_lin_vel * self.obs_scales.lin_vel,
> RuntimeError: Tensors must have same number of dimensions: got 2 and 1
> ```
> 
> I find the code is here
> 
> ```
>     def compute_observations(self):
>         """ Computes observations
>         """
>         print((self.base_lin_vel * self.obs_scales.lin_vel).shape)
>         print((self.base_ang_vel  * self.obs_scales.ang_vel).shape)
>         print((self.commands[:, :3] * self.commands_scale).shape)
>         print(((self.dof_pos - self.default_dof_pos) * self.obs_scales.dof_pos).shape)
>         print((self.dof_vel * self.obs_scales.dof_vel).shape)
>         print((self.actions).shape)
>         self.obs_buf = torch.cat((  self.base_lin_vel * self.obs_scales.lin_vel,
>                                     self.base_ang_vel  * self.obs_scales.ang_vel,
>                                     self.projected_gravity,
>                                     self.commands[:, :3] * self.commands_scale,
>                                     (self.dof_pos - self.default_dof_pos) * self.obs_scales.dof_pos,
>                                     self.dof_vel * self.obs_scales.dof_vel,
>                                     self.actions
>                                     ),dim=-1)
>         # add perceptive inputs if not blind
>         # add noise if needed
>         if self.add_noise:
>             self.obs_buf += (2 * torch.rand_like(self.obs_buf) - 1) * self.noise_scale_vec
> ```
> 
> the output is
> 
> ```
> torch.Size([4096, 3])
> torch.Size([4096, 3])
> torch.Size([4096, 3])
> torch.Size([4096, 12])
> torch.Size([4096, 12])
> torch.Size([12])
> ```

I resolved the issue by commenting out `# self.compute_observations()` in the `post_physics_step(self)` function located at `/unitree_rl_gym-main/legged_gym/envs/base/legged_robot.py`.

**Comment by Logic-TARS** [comment]
Have you solved the problem？
